Update the tasks to point to main and add a gitflow enforcer

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -2,13 +2,23 @@ name: CI/CD
 
 on:
   - push
+  - pull_request:
+      types: [ opened, reopened, edited, synchronize ]
 
 jobs:
+  gitflow-enforcer:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Check branch
+          if: github.base_ref == 'main' && github.head_ref != 'dev' || github.base_ref == 'production' && github.head_ref != 'main'
+          run: |
+            echo "ERROR: You can only merge to main from dev and to production from main"
+            exit 1
+            
   run-linters:
     name: Run linters
     runs-on: ubuntu-latest
-
-
+    needs: gitflow-enforcer
     steps:
       - name: Check out Git repository
         uses: actions/checkout@v2
